export const petBreeds = {
    Dog: [
        "Labrador Retriever",
        "French Bulldog",
        "German Shepherd",
        "Golden Retriever",
        "Bulldog",
        "Poodle",
        "Beagle",
        "Rottweiler",
        "Dachshund",
        "Corgi",
        "Australian Shepherd",
        "Yorkshire Terrier",
        "Boxer",
        "Siberian Husky",
        "Great Dane",
        "Cavalier King Charles Spaniel",
        "Doberman",
        "Miniature Schnauzer",
        "Shih Tzu",
        "Boston Terrier",
        "Pomeranian",
        "Havanese",
        "Shetland Sheepdog",
        "Brittany Spaniel",
        "Bernese Mountain Dog",
        "Cocker Spaniel",
        "Maltese",
        "Basset Hound",
        "Border Collie",
        "Chihuahua",
        "Akita",
        "Weimaraner",
        "Newfoundland",
        "Shiba Inu",
        "St. Bernard",
        "Papillon",
        "Dalmatian",
        "Whippet",
        "Vizsla",
        "Bullmastiff",
        "Alaskan Malamute",
        "Scottish Terrier",
        "Jack Russell Terrier",
        "Greyhound",
        "Belgian Malinois",
        "Pekingese",
        "Irish Setter",
        "Bloodhound",
        "Afghan Hound",
        "Old English Sheepdog",
        "Lhasa Apso",
    ],
    Cat: [
        "Persian",
        "Siamese",
        "Maine Coon",
        "Bengal",
        "Sphynx",
        "Ragdoll",
        "Scottish Fold",
        "British Shorthair",
        "Abyssinian",
        "Birman",
        "Oriental Shorthair",
        "Savannah",
        "Russian Blue",
        "Norwegian Forest Cat",
        "Devon Rex",
        "Cornish Rex",
        "American Shorthair",
        "Siberian",
        "Turkish Angora",
        "Balinese",
        "Manx",
        "Tonkinese",
        "Himalayan",
        "Burmese",
        "Egyptian Mau",
        "Selkirk Rex",
        "Bombay",
        "Japanese Bobtail",
        "Korat",
        "LaPerm",
        "Ocicat",
        "Somali",
        "Turkish Van",
        "Snowshoe",
        "Singapura",
        "Munchkin",
        "Toyger",
        "Ragamuffin",
    ],
};


